export interface NewsArticle {
    "kind": string,
    "domain": string,
    "source": {
        "title": string,
        "region": string,
        "domain": string,
        "path": null | any
    },
    "title": string,
    "published_at": string,
    "slug": string,
    "id": number,
    "url": string,
    "created_at": string,
    "votes": {
        "negative": number,
        "positive": number,
        "important": number,
        "liked": number,
        "disliked": number,
        "lol": number,
        "toxic": number,
        "saved": number,
        "comments": number
    }
}

export interface Coin {
    amount: string,
    coin: string,
    created_at: string,
    id: number
}

export interface Conversion {
    "aed": number,
    "ars": number,
    "aud": number,
    "bch": number,
    "bdt": number,
    "bhd": number,
    "bmd": number,
    "bnb": number,
    "brl": number,
    "btc": number,
    "cad": number,
    "chf": number,
    "clp": number,
    "cny": number,
    "czk": number,
    "dkk": number,
    "dot": number,
    "eos": number,
    "eth": number,
    "eur": number,
    "gbp": number,
    "hkd": number,
    "huf": number,
    "idr": number,
    "ils": number,
    "inr": number,
    "jpy": number,
    "krw": number,
    "kwd": number,
    "lkr": number,
    "ltc": number,
    "mmk": number,
    "mxn": number,
    "myr": number,
    "ngn": number,
    "nok": number,
    "nzd": number,
    "php": number,
    "pkr": number,
    "pln": number,
    "rub": number,
    "sar": number,
    "sek": number,
    "sgd": number,
    "thb": number,
    "try": number,
    "twd": number,
    "uah": number,
    "usd": number,
    "vef": number,
    "vnd": number,
    "xag": number,
    "xau": number,
    "xdr": number,
    "xlm": number,
    "xrp": number,
    "yfi": number,
    "zar": number,
    "bits": number,
    "link": number,
    "sats": number  
}

export interface ConversionDates {
    "aed": string,
    "ars": string,
    "aud": string,
    "bch": string,
    "bdt": string,
    "bhd": string,
    "bmd": string,
    "bnb": string,
    "brl": string,
    "btc": string,
    "cad": string,
    "chf": string,
    "clp": string,
    "cny": string,
    "czk": string,
    "dkk": string,
    "dot": string,
    "eos": string,
    "eth": string,
    "eur": string,
    "gbp": string,
    "hkd": string,
    "huf": string,
    "idr": string,
    "ils": string,
    "inr": string,
    "jpy": string,
    "krw": string,
    "kwd": string,
    "lkr": string,
    "ltc": string,
    "mmk": string,
    "mxn": string,
    "myr": string,
    "ngn": string,
    "nok": string,
    "nzd": string,
    "php": string,
    "pkr": string,
    "pln": string,
    "rub": string,
    "sar": string,
    "sek": string,
    "sgd": string,
    "thb": string,
    "try": string,
    "twd": string,
    "uah": string,
    "usd": string,
    "vef": string,
    "vnd": string,
    "xag": string,
    "xau": string,
    "xdr": string,
    "xlm": string,
    "xrp": string,
    "yfi": string,
    "zar": string,
    "bits": string,
    "link": string,
    "sats": string
}

export interface Locales {
    "en": string,
    "de": string,
    "es": string,
    "fr": string,
    "it": string,
    "pl": string,
    "ro": string,
    "hu": string,
    "nl": string,
    "pt": string,
    "sv": string,
    "vi": string,
    "tr": string,
    "ru": string,
    "ja": string,
    "zh": string,
    "zh-tw": string,
    "ko": string,
    "ar": string,
    "th": string,
    "id": string
}

export interface Ticker {
    "base": string,
    "target": string,
    "market": {
        "name": string,
        "identifier": string,
        "has_trading_incentive": boolean
    },
    "last": number,
    "volume": number,
    "converted_last": {
        "btc": number,
        "eth": number,
        "usd": number
    },
    "converted_volume": {
        "btc": number,
        "eth": number,
        "usd": number
    },
    "trust_score": string,
    "bid_ask_spread_percentage": number,
    "timestamp": string,
    "last_traded_at": string,
    "last_fetch_at": string,
    "is_anomaly": boolean,
    "is_stale": boolean,
    "trade_url": string,
    "token_info_url": null | any,
    "coin_id": string
}

export interface CoinData {
    "id": string,
    "symbol": string,
    "name": string,
    "asset_platform_id": null | string,
    "platforms": {
        "": string
    },
    "block_time_in_minutes": number,
    "hashing_algorithm": null | string,
    "categories": string[],
    "public_notice": null | any,
    "additional_notices": string[],
    "localization": Locales,
    "description": Locales,
    "links": {
        "homepage": string[],
        "blockchain_site": string[],
        "official_forum_url": string[],
        "chat_url": string[],
        "announcement_url": string[],
        "twitter_screen_name": string,
        "facebook_username": string,
        "bitcointalk_thread_identifier": null | any,
        "telegram_channel_identifier": string,
        "subreddit_url": string,
        "repos_url": {
            "github": string[],
            "bitbucket": string[]
        }
    },
    "image": {
        "thumb": string,
        "small": string,
        "large": string
    },
    "country_origin": string,
    "genesis_date": string,
    "sentiment_votes_up_percentage": number,
    "sentiment_votes_down_percentage": number,
    "market_cap_rank": number,
    "coingecko_rank": number,
    "coingecko_score": number,
    "developer_score": number,
    "community_score": number,
    "liquidity_score": number,
    "public_interest_score": number,
    "market_data": {
        "current_price": Conversion,
        "total_value_locked": null | any,
        "mcap_to_tvl_ratio": null | any,
        "fdv_to_tvl_ratio": null | any,
        "roi": null | any,
        "ath": Conversion,
        "ath_change_percentage": Conversion,
        "ath_date": ConversionDates,
        "atl": Conversion,
        "atl_change_percentage": Conversion,
        "atl_date": ConversionDates,
        "market_cap": Conversion,
        "market_cap_rank": number,
        "fully_diluted_valuation": Conversion,
        "total_volume": Conversion,
        "high_24h": Conversion,
        "low_24h": Conversion,
        "price_change_24h": number,
        "price_change_percentage_24h": number,
        "price_change_percentage_7d": number,
        "price_change_percentage_14d": number,
        "price_change_percentage_30d": number,
        "price_change_percentage_60d": number,
        "price_change_percentage_200d": number,
        "price_change_percentage_1y": number,
        "market_cap_change_24h": number,
        "market_cap_change_percentage_24h": number,
        "price_change_24h_in_currency": Conversion,
        "price_change_percentage_1h_in_currency": Conversion,
        "price_change_percentage_24h_in_currency": Conversion,
        "price_change_percentage_7d_in_currency": Conversion,
        "price_change_percentage_14d_in_currency": Conversion,
        "price_change_percentage_30d_in_currency": Conversion,
        "price_change_percentage_60d_in_currency": Conversion,
        "price_change_percentage_200d_in_currency": Conversion,
        "price_change_percentage_1y_in_currency": Conversion,
        "market_cap_change_24h_in_currency": Conversion,
        "market_cap_change_percentage_24h_in_currency": Conversion,
        "total_supply": number,
        "max_supply": number,
        "circulating_supply": number,
        "last_updated": string
    },
    "community_data": {
        "facebook_likes": null | any,
        "twitter_followers": number,
        "reddit_average_posts_48h": number,
        "reddit_average_comments_48h": number,
        "reddit_subscribers": number,
        "reddit_accounts_active_48h": number,
        "telegram_channel_user_count": null | any
    },
    "developer_data": {
        "forks": number,
        "stars": number,
        "subscribers": number,
        "total_issues": number,
        "closed_issues": number,
        "pull_requests_merged": number,
        "pull_request_contributors": number,
        "code_additions_deletions_4_weeks": {
            "additions": number,
            "deletions": number
        },
        "commit_count_4_weeks": number,
        "last_4_weeks_commit_activity_series": number[]
    },
    "public_interest_stats": {
        "alexa_rank": number,
        "bing_matches": null | any
    },
    "status_updates": string[],
    "last_updated": string,
    "tickers": Ticker[],
    "amount_owned"?: string,
    "price"?: number,
    "total_value"?: number
}

export interface SQLResponse {
    affectedRows: number,
    changedRows: number,
    fieldCount: number,
    insertId: number,
    message: string,
    protocol41: boolean,
    serverStatus: number,
    warningCount: number
}

export interface MarketCap100 {
    ath: number,
    ath_change_percentage: number,
    ath_date: string,
    atl: number,
    atl_change_percentage: number,
    atl_date: string,
    circulating_supply: number,
    current_price: number,
    fully_diluted_valuation: number,
    high_24h: number,
    id: string,
    image: string,
    last_updated: string,
    low_24h: number,
    market_cap: number,
    market_cap_change_24h: number,
    market_cap_change_percentage_24h: number,
    market_cap_rank: number,
    max_supply: number,
    name: string,
    price_change_24h: number,
    price_change_percentage_24h: number,
    roi: null,
    symbol: string,
    total_supply: number,
    total_volume: number
}
  