/**
 * Stable error codes for API clients. Used in RFC 7807 response `code` field.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  STRATEGY_NOT_FOUND = 'STRATEGY_NOT_FOUND',
  STRATEGY_VERSION_NOT_FOUND = 'STRATEGY_VERSION_NOT_FOUND',
  STRATEGY_VALIDATION_ERROR = 'STRATEGY_VALIDATION_ERROR',
  BACKTEST_INVALID_DEFINITION = 'BACKTEST_INVALID_DEFINITION',
  BACKTEST_INSUFFICIENT_BARS = 'BACKTEST_INSUFFICIENT_BARS',
  BACKTEST_BAR_LIMIT_EXCEEDED = 'BACKTEST_BAR_LIMIT_EXCEEDED',
  BACKTEST_RESOURCE_LIMIT_EXCEEDED = 'BACKTEST_RESOURCE_LIMIT_EXCEEDED',
  BACKTEST_TIMEOUT = 'BACKTEST_TIMEOUT',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
