import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { parseArgs } from "node:util";

export function settings(args) {
  const { values } = parseArgs({
    args,
    options: {
      mode: { type: "string", default: "simulator" },
      "api-origin": { type: "string" },
      "rp-id": { type: "string" },
      "team-id": { type: "string" },
      "bundle-id": { type: "string", default: "com.bitstockerz.research" },
    },
  });
  if (!["simulator", "device"].includes(values.mode))
    throw new Error("mode must be simulator or device");
  const simulator = values.mode === "simulator";
  const api = new URL(
    values["api-origin"] ?? (simulator ? "http://localhost:4310" : ""),
  );
  if (
    api.username ||
    api.password ||
    api.pathname !== "/" ||
    api.search ||
    api.hash ||
    (simulator
      ? api.origin !== "http://localhost:4310"
      : api.protocol !== "https:")
  ) {
    throw new Error(
      "Use http://localhost:4310 for simulator mode, or an HTTPS origin without a path or credentials for device mode",
    );
  }
  const rp = simulator ? "passkeys.invalid" : values["rp-id"];
  if (
    !rp ||
    !/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(rp) ||
    (!simulator && rp.toLowerCase().endsWith(".invalid"))
  ) {
    throw new Error(
      "Device mode requires --rp-id with a real domain you control",
    );
  }
  const bundle = values["bundle-id"];
  if (!/^[a-zA-Z][a-zA-Z0-9-]*(?:\.[a-zA-Z0-9-]+)+$/.test(bundle))
    throw new Error("Invalid bundle identifier");
  const team = values["team-id"];
  if (team && !/^[A-Z0-9]{10}$/.test(team))
    throw new Error("Apple Team ID must be ten uppercase letters/digits");
  return {
    mode: values.mode,
    apiOrigin: api.origin,
    rpId: rp.toLowerCase(),
    bundleId: bundle,
    teamId: team,
  };
}

export function prepare(args) {
  const config = settings(args);
  const root = fileURLToPath(new URL("../../", import.meta.url));
  const write = (name, contents) =>
    writeFileSync(resolve(root, name), contents);
  write(
    "apps/web/src/environments/environment.ios.local.ts",
    `// Generated by ios:prepare; contains public configuration only.\nexport const environment = ${JSON.stringify({ production: config.mode !== "simulator", apiBaseUrl: config.apiOrigin, nativeMode: config.mode }, null, 2)} as { production: boolean; apiBaseUrl: string; nativeMode: 'web' | 'simulator' | 'device' };\n`,
  );
  write(
    "apps/web/ios/App/App/Prototype.xcconfig",
    `BITSTOCKERZ_RP_ID = ${config.rpId}\nBITSTOCKERZ_BUNDLE_ID = ${config.bundleId}\n${config.teamId ? `DEVELOPMENT_TEAM = ${config.teamId}\n` : ""}`,
  );
  write(
    "apps/web/.ios-prototype.local.json",
    JSON.stringify(config, null, 2) + "\n",
  );
  mkdirSync(resolve(root, "artifacts/ios-setup"), { recursive: true });
  if (config.teamId && config.mode === "device") {
    write(
      "artifacts/ios-setup/apple-app-site-association",
      JSON.stringify(
        {
          webcredentials: { apps: [`${config.teamId}.${config.bundleId}`] },
        },
        null,
        2,
      ) + "\n",
    );
  }
  console.log(
    `Prepared ${config.mode} prototype for ${config.apiOrigin}. Next: npm run ios:sync`,
  );
  if (config.mode === "device")
    console.log(
      "Serve the association file publicly on the RP domain. Do not put the production beta proxy key in this app.",
    );
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    prepare(process.argv.slice(2));
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
